# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hi/User
Accept: application/json

###

POST http://127.0.0.1:8000/miniature
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="harbor.jpg"

< ./resources/harbor.jpg
--WebAppBoundary--

###

POST http://127.0.0.1:8000/pixelate/300/300
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat.jpg"

< ./resources/cat.jpg
--WebAppBoundary--

###
